/**
 * Created by sunNode on 16/7/31.
 */
var countryData=[{
    'BEIJING':'PEK',
    'SHANGHAI':'SHA',
    'TIANJIN':'TSN',
    'XIAN':'SIA',
    'HANGCHOW':'HGH',
    'DALIAN':'DLC',
    'TSINGTAO':'TAO',
    'FOOCHOW':'FOC',
    'XIAMEN':'XMN',
    'KUNMING':'KMG',
    'NANKING':'NKG',
    'SWATOW':'SWA',
    'GUILIN':'KWL',
    'CHENGTU':'CTU',
    'CANTON':'CAN',
    'HAIKOU':'HAK',
    'CHANGSHA':'CSX',
    'YANTAI':'YNT',
    'CHONGQING':'CKG',
    'WENZHOU':'WNZ',
    'SANYA':'SYX',
    'HARBIN':'HRB',
    'SHENGZHEN':'SZX',
    'NANCHANG':'KHN',
    'HONGKONG':	'HKG',
    'MACAO':'MFM',
    'TAIPEI':'TPE',
    'KAOHSIUNG':'KHH',
    'TOKYO':'YO',
    'OSAKA':'OSA',
    'NAGOYA':'NGO',
    'SAPPORO':'SPK',
    'FUKUOKA':'FUK',
    'OKINAWA':'OKA',
    'SEOUL':'SEL',
    'PUSAN':'PUS',
    'SINGAPORE':'SIN',
    'KUALA LUNPUR':	'KUL',
    'PENANG':'PEN',
    'IPOH':'IPH',
    'BANGKOK':'BKK',
    'qingmai':'CNX',
    'PHUKET':'HKT',
    'JAKARTA':'JKT',
    'DENPASAR':'DPS',
    'MEDAN':'MES',
    'PALEMBANG':'PLM',
    'SURABAYA':	'SUB',
    'RANGOON':'RGN',
    'HANOI':'HAN',
    'PHNOM PENH':'PNH',
    'SAIGON':'SGN',
    'VIENTIANE':'VTE',
    'MANILA':'MNL',
    'CEBU':'CEB',
    'DILI':'DIL',
    'KOTA KINABALU':'BKI',
    'DACCA':'DAC',
    'SIBU':'SBW',
    'SAIPAN':'SPN',
    'BANDER SERI BEGAWAN':'BWN',
    'DELHI':'DEL',
    'KABUL':'KBL',
    'CHITTAGON':'CGP',
    'KARACHI':'KHI',
    'TONGGATAPU':'TBU',
    'NAURU':'INU',
    'BAGUIO':'BAG',
    'BOMBAY','BOM',
    'COLOMBA':'CMB',
    'CALCUTTA':	'CCU',
    'MADRAS':'MAA',
    'KATHMANDU':'KTM',
    'MEXICO CITY':'MEX',
    'SAN SALVADOR':'SAL',
    'PANAMA CITY':'PTY',
    'HAVANA':'BOG',
    'BOGOTA':'UIO',
    'QUITO':'LIM',
    'LIMA':'SCL',
    'SANTIAGO':'SAN',
    'BUENDS AIRES':'BUE',
    'SAN PAULO':'SAO',
    'RIO DE JANEIRO':'RIO',
    'BRASSILIA':'BSB',
    'CARACAS':'CCS',
    'CAYENNE':'CAY',
    'MONTEBIDEO':'MVD',
    'MANAGUA':'MGA',
    'GUATEMALA':'GUA',
    'SANTO DOMINGO':'SDQ',
    'LA PAZ':'LPB',
    'KINGSTON':'KIN',
    'SAN JUAN':'SJU',
    'PORT AU PRINCE':'PAP',
    'MONTEGO BAY':'MBJ',
    'SAN JOSE':'SJO',
    'EGUCIGALPA':'TGU',
    'ACAPUCCO':'ACA',
    'BRIDGE TOWN':'BGI',
    'PORT OF SPAIN':'POS',
    'ASUNCION':'ASU',
    'MANAUS':'MAO',
    'RECIFE':'REL',
    'PARAMARIBO':'PBM',
    'GEORGE TOWN':'GRG',
    'LONDON':'LON',
    'PARIS':'PAR',
    'GENEVA':'GVA',
    'ZURICH':'ZRH',
    'BERLIN':'BER',
    'HAMBERG':'HAM',
    'FRANKFURT':'FRA',
    'COLOGNE':'CGN',
    'MUNICH':'MUC',
    'DUBLIN':'DUB',
    'SHANNON':'SNN',
    'WARSAW':'WAW',
    'AMSTERDAM':'AMS',
    'BRUSSELS':'BRU',
    'VIENNA':'VIE',
    'PRAGUE':'PRG',
    'BUDAPEST':'BUD',
    'ATHENS':'ATH',
    'MILAN':'MIL',
    'ROME':'ROM',
    'BARCELONA':'BCN',
    'BONN':'BNJ',
    'DUSSDOLF':'DUS',
    'STUTTGART':'STR',
    'EDINBURGH':'EDI',
    'SOFIA':'SOF',
    'ISTANBUL':'IST',
    'LISBON':'LIS',
    'MADRID':'MAD',
    'GIBRALTAR':'GIB',
    'BELGRADE':'BEG',
    'BUCHAREST':'BUH',
    'MANCHESTER':'MAN',
    'COPENHAGEN':'CPH',
    'OSLO':'OSL',
    'STOCKHOLM':'STO',
    'HELSINKI':'HEL',
    'GLASGOW':'GLA',
    'NICE':'NCE',
    'NEWYORK':'NYK',
    'PHILADELPHIA':'PHL',
    'BOSTON':'BOS',
    'WASHINGTON':'WAS',
    'CHICAGO':'CHI',
    'DETROIT':'DTT',
    'PITTSBURGH':'PIT',
    'CLEVELAND':'CLE',
    'BUFFALO':'BUF',
    'INDIANAPOLIS':'IND',
    'ST.LOUIS':'STL',
    'MINNEAPOLIS':'MSP',
    'KANSAS CITY':'MKC',
    'HUSTON':'HOU',
    'DALAS':'DFW',
    'NEW ORLEANS':'MSY',
    'OKLAHOMA CITY':'OKC',
    'ATLANTA':'ATL',
    'MIAMI':'MIA',
    'TUCSON':'TUS',
    'LITTLE ROCK':'LIT',
    'CINCINNATI':'CVG',
    'DENVER':'DEN',
    'PHOENIX':'PHX',
    'SALT LAKE CITY':'SLC',
    'LAS VEGAS':'LAS',
    'ALBUOERQUE':'ABQ',
    'PORTLAND':	'PDX',
    'SAN FRANCISCO':'SFO',
    'LOS ANGELES':'LAX',
    'SEATTLE':'SEA',
    'ANCHORAGE':'ANC',
    'GUAM':'GUM',
    'ORLANDO':'ORL',
    'SAN JOSE':'SJC',
    'SAN ANTONIO':'SAT',
    'MILWAKEE':'MKE',
    'BALTIMORE':'MTN',
    'HONOLULU':'HNL',
    'VANCOUVER':'YVR',
    'TORONTO':'YYZ',
    'OTTAWA':'YOW',
    'MONTREAL':'YMQ',
    'WINNIPEG':'YMG',
    'CALGARY':'YYC',
    'EDMONTON':'YEA',
    'GANDER':'YQX',
    'HALIFAX':'YHZ',
    'CAIRO':'CAI',
    'CAPETOWN':'CPT',
    'BEIRUT':'BEY',
    'TEL AVIV':'TLV',
    'DANASCUS':'DAM',
    'AMMAN':'AMM',
    'JEDDAH':'JED',
    'BAHRAIN':'BAH',
    'JOHAN NFABURG':'JNB',
    'KINSHASA':'FIA',
    'MALTA':'MLA',
    'TUNIS':'TUN',
    'DAKAR':'DKR',
    'BAN-GUI':'BGF',
    'BRAXXABILLE':'BZV',
    'MAURITIUS':'MRU',
    'DUBAI':'DXB',
    'KUWAIT':'KWI',
    'BAGHDAD':'BGW',
    'TEHRAN':'THR',
    'TRIPOLI':'TIP',
    'ALGIERS':'ALG',
    'CASABLANCA':'CAS',
    'LASPALMAS':'LPA',
    'CONAKRY':'CKY',
    'FREETOWN':'FNA',
    'BAMAKO':'BKO',
    'ABIDJAN':'ABJ',
    'MONROVIA':'MLW',
    'NIAMEY':'NIM',
    'ACCRA':'ACC',
    'OUAGADOUGOU':'OUA',
    'FORT LAMY':'FTL',
    'YAOUNDE':'YAO',
    'COTONOU':'COO',
    'LAGOS':'LOS',
    'LIBREVILLE':'LVB',
    'LUAN DA':'LAD',
    'WINDHOEK':'WDH',
    'KHARTOUM':'KRT',
    'ISTANBUL':'IST',
    'ANKARA':'ANK',
    'ADEN':'ADE',
    'MUSCAT':'MCT',
    'ABADAN':'ABD',
    'TANANARIVE':'TNR',
    'EDINBURGH':'EDI',
    'LOME':'LFW',
    'MASERU':'MSU',
    'MANZINI':'MTS',
    'DOHA':'DOH',
    'DHAHRAN':'DHA',
    'RIYADH':'RUH',
    'LILONGWE':'LLW',
    'DJAMENA':'NDJ',
    'DAR ES SALAAM':'DAR',
    'LUSAKA':'LUN',
    'MOGADISHU':'MGO',
    'ENTEBBE/KAMPALA':'EBB',
    'ADDIS ABABA':'ADD',
    'NAIROBI':'NBO',
    'BLANTYRE':'BLZ',
    'LOURENCO MAROUES':'LUM',
    'SALISBURY':'SAY',
    'DARWIN':'DRW',
    'PERTH':'PER',
    'SYDNEY':'SYD',
    'BRISBANE':'BNE',
    'CANBERRA':'CBR',
    'MELBOURNE':'MEB',
    'CHRISTCHURCH':'CHC',
    'WELLINGTON':'WLG',
    'AUCKLAND':'AKL',
    'NOUMEA':'NOU',
    'NADI':'NAN',
    'PAGO APGO':'PPG',
    'CAIRNS':'CNS',
    'HAFR ALBATIN':'HBT',
    'POTR MORESBY':'POM',
    'SUVA':'SUV',
    'PAPEETE':'PPT',
    'TAICHUNG':'TXG',
    'HONG KONG':'HKG',
    'LANZHOU':'LHW',
    'NANCHANG':'KHN'

}]